### ISSUE TITLE
Aternos problem

### ISSUE THREAD

**Issue by Bruh1HuhuHa** [nu11une/wardenloot#11] opened 2022-07-16 15:30 UTC
well...the MoreMcmeta isn't available on aternos, it says that moremcmeta is a client side mod, but then when I try and open the server it says that it need the moremcmeta mod but its a client side... I'm wondering if you can do something about it

**Comment by nu11une** [comment] 2022-07-16 15:35
Duplicate of #10. This was fixed in the newest commit and a new release will be made today or tomorrow with the fix.

**Closed as completed by nu11une** 2022-07-16 15:35 UTC
Labels: bug, duplicate

**Comment by Bruh1HuhuHa** [comment] 2022-07-17 06:09
is it gonna be 1.19 or 1.19.1? pls make it 1.19

**Comment by nu11une** [comment] 2022-07-17 13:46
the release works for both 1.19 and 1.19.1
